# Generated by Django 3.2.4 on 2021-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210621_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
