# Generated by Django 3.2.4 on 2021-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('itemsJson', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=60)),
            ],
        ),
    ]
