# Generated by Django 3.2.4 on 2021-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('updateId', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.IntegerField(default='')),
                ('updateDescription', models.CharField(max_length=100)),
                ('timeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
