# Generated by Django 3.2.4 on 2021-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('headingone', models.CharField(max_length=100)),
                ('contentone', models.CharField(max_length=7000)),
                ('headingtwo', models.CharField(max_length=100)),
                ('contenttwo', models.CharField(max_length=7000)),
                ('headingthree', models.CharField(max_length=100)),
                ('contentthree', models.CharField(max_length=7000)),
                ('publishDate', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
